name: pytest
on: workflow_dispatch
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: pre checkout repository
        run: |
          pwd
          ls -lh
      - name: checkout repository
        uses: actions/checkout@v4
      - name: post checkout repository
        run: |
          pwd
          ls -lh
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
